import "./globals.css";
import { Inter } from "next/font/google";

import NavMenu from "@/Components/NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Post Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavMenu />
        {children}
      </body>
    </html>
  );
}
